name: CaDet
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.4=py310h8e9501a_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - aom=3.5.0=h7ea286d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h8e9501a_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - blosc=1.21.3=h1d6ff8b_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - brotli=1.0.9=h1a8c8d9_8
  - brotli-bin=1.0.9=h1a8c8d9_8
  - brotlipy=0.7.0=py310h8e9501a_1005
  - brunsli=0.1=h9f76cd9_0
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.18.1=h3422bc3_0
  - c-blosc2=2.7.1=h303ed30_0
  - ca-certificates=2022.12.7=h4653dfc_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - caiman=1.9.13=py310h2b830bf_0
  - cairo=1.16.0=h73a0509_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2399d43_3
  - cfitsio=4.2.0=h2f961c4_0
  - charls=2.4.1=hb7217d7_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.0.1=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.7=py310h2887b22_0
  - cryptography=39.0.2=py310hfc83b78_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py310h8e9501a_1
  - dask-core=2023.3.1=pyhd8ed1ab_0
  - dav1d=1.0.0=he4db4b2_1
  - debugpy=1.6.6=py310h0f1eb42_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hb7217d7_0
  - ffmpeg=5.1.2=gpl_hf318d42_106
  - flatbuffers=22.12.06=hb7217d7_2
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.0=py310h8e9501a_0
  - freetype=2.12.1=hd633e50_1
  - frozenlist=1.3.3=py310h8e9501a_0
  - fsspec=2023.3.0=pyhd8ed1ab_1
  - future=0.18.3=pyhd8ed1ab_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.21.1=h0186832_0
  - giflib=5.2.1=h1a8c8d9_3
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.7.8=h9f1a10d_0
  - google-auth=2.16.2=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - graphite2=1.3.13=h9f76cd9_1001
  - grpcio=1.51.1=py310h63a0e3a_1
  - h5py=3.8.0=nompi_py310h3c889c5_101
  - harfbuzz=6.0.0=hddbc195_0
  - hdf5=1.14.0=nompi_h6b85c65_103
  - hdmf=3.5.1=pyh1a96a4e_0
  - holoviews=1.15.2=pyhd8ed1ab_0
  - icu=70.1=h6b3803e_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py310hd30fb6a_0
  - imageio=2.26.0=pyh24c5eb1_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipyparallel=8.4.1=pyhd8ed1ab_0
  - ipython=8.11.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jasper=2.0.33=hc3cd1e9_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h1a8c8d9_3
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py310hbe9552e_8
  - jupyter_client=8.0.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py310hbe9552e_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.4.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - jxrlib=1.1=h27ca646_2
  - keras=2.11.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py310h2887b22_1
  - krb5=1.20.1=h69eda48_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.15=h481adae_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20220623.0=cxx17_h28b99d4_6
  - libaec=1.0.6=hb7217d7_1
  - libavif=0.11.1=h3d80962_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_8
  - libbrotlidec=1.0.9=h1a8c8d9_8
  - libbrotlienc=1.0.9=h1a8c8d9_8
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.88.1=h9049daf_0
  - libcxx=15.0.7=h75e25f2_0
  - libdeflate=1.17=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=hca03da5_6
  - libgfortran=5.0.0=12_2_0_hd922786_31
  - libgfortran5=12.2.0=h0eea778_31
  - libglib=2.74.1=h4646484_1
  - libgrpc=1.51.1=hb15be72_1
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.52.0=hae82a92_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libopencv=4.7.0=py310hb4a851b_1
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=3.21.12=hb5ab8b9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.5.0=h5dffbdd_2
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.11.0=hc470f4d_3
  - libwebp-base=1.3.0=h1a8c8d9_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.10.3=h87b0503_0
  - libzlib=1.2.13=h03a7124_4
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=15.0.7=h7cfbb63_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hb7217d7_0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.2=py310h8e9501a_0
  - matplotlib=3.7.1=py310hb6292c7_0
  - matplotlib-base=3.7.1=py310h78c5c2f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - multidict=6.0.4=py310h8e9501a_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=1.1.1=py310h8e9501a_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclassic=0.5.3=pyhb4ecaf3_3
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.8.1=h63371fa_1
  - networkx=3.0=pyhd8ed1ab_0
  - nose=1.3.7=py_1006
  - notebook=6.5.3=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - opencv=4.7.0=py310hb6292c7_1
  - openh264=2.3.1=hb7217d7_2
  - openjpeg=2.5.0=hbc2ba62_2
  - openssl=3.0.8=h03a7124_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - p11-kit=0.24.1=h29577a5_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py310h2b830bf_0
  - pandoc=2.19.2=hce30654_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=0.14.4=pyhd8ed1ab_0
  - param=1.13.0=pyh1a96a4e_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - pcre2=10.40=hb34f9b4_0
  - peakutils=1.3.4=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h5a7539a_1
  - pims=0.6.1=pyhd8ed1ab_0
  - pip=23.0.1=py310hca03da5_0
  - pixman=0.40.0=h27ca646_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - pooch=1.7.0=pyhd8ed1ab_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - protobuf=4.21.12=py310h0f1eb42_0
  - psutil=5.9.4=py310h8e9501a_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.7.0=py310h69fb684_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pynwb=2.2.0=py310hbe9552e_1
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqtgraph=0.13.2=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h8e9501a_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.9=h3ba56d0_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-flatbuffers=23.1.21=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyviz_comms=2.2.1=pyhd8ed1ab_1
  - pywavelets=1.4.1=py310hf1a086a_0
  - pyyaml=6.0=py310h8e9501a_5
  - pyzmq=25.0.1=py310hc407298_0
  - re2=2023.02.01=hb7217d7_0
  - readline=8.2=h1a28f6b_0
  - requests=2.28.2=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py310h8e9501a_3
  - ruamel.yaml.clib=0.2.7=py310h8e9501a_1
  - scikit-image=0.19.3=py310h2b830bf_2
  - scikit-learn=1.2.2=py310ha00a7cd_0
  - scipy=1.10.1=py310ha0d8a01_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.6.3=py310hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - slicerator=1.1.0=pyhd8ed1ab_0
  - snappy=1.1.10=h17c5cce_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sqlite=3.40.1=h7a7dc30_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=1.4.1=h7ea286d_0
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py310hfc83b78_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.11.0=cpu_py310h6ecea76_0
  - tensorflow-base=2.11.0=cpu_py310hb1e6bfe_0
  - tensorflow-estimator=2.11.0=cpu_py310h238a819_0
  - termcolor=2.2.0=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2023.2.28=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=hb8d0fd4_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py310h8e9501a_1
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2022g=h04d1e81_0
  - unicodedata2=15.0.0=py310h8e9501a_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - werkzeug=2.2.3=pyhd8ed1ab_0
  - wheel=0.38.4=py310hca03da5_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - wrapt=1.15.0=py310h8e9501a_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.10=h80987f9_1
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.8.2=py310h8e9501a_0
  - z5py=2.0.16=py310h8acfa5e_0
  - zeromq=4.3.4=hbdafb3b_1
  - zfp=1.0.0=hb6e4faa_3
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zlib-ng=2.0.6=he4db4b2_0
  - zstd=1.5.2=hf913c23_6
  - pip:
    - aiofiles==22.1.0
    - aiosqlite==0.18.0
    - arrow==1.2.3
    - babel==2.12.1
    - charset-normalizer==3.1.0
    - cmasher==1.6.3
    - colorspacious==1.1.2
    - decorator==4.4.2
    - e13tools==0.9.6
    - fastplotlib==0.1.0a9
    - fqdn==1.5.1
    - freetype-py==2.3.0
    - imageio-ffmpeg==0.4.8
    - ipykernel==6.21.3
    - ipython-genutils==0.2.0
    - isoduration==20.11.0
    - json5==0.9.11
    - jsonpointer==2.3
    - jupyter-rfb==0.3.3
    - jupyter-server-fileid==0.8.0
    - jupyter-server-ydoc==0.6.1
    - jupyter-ydoc==0.2.3
    - jupyterlab==3.6.1
    - jupyterlab-server==2.20.0
    - moviepy==1.0.3
    - nbconvert==7.2.10
    - numpy==1.24.2
    - opencv-python==4.7.0.72
    - proglog==0.1.10
    - pygfx==0.1.12
    - pyside6==6.4.2
    - pyside6-addons==6.4.2
    - pyside6-essentials==6.4.2
    - qtpy==2.3.1
    - rubicon-objc==0.4.5
    - shiboken6==6.4.2
    - sortedcontainers==2.4.0
    - soupsieve==2.4
    - superqt==0.4.1
    - uharfbuzz==0.35.0
    - uri-template==1.2.0
    - webcolors==1.12
    - webencodings==0.5.1
    - wgpu==0.9.4
    - y-py==0.5.9
    - ypy-websocket==0.8.2
